/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as SplashRouteImport } from './routes/splash'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KycRouteImport } from './routes/kyc'
import { Route as JoinRouteImport } from './routes/join'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as EnableFaceidRouteImport } from './routes/enable-faceid'
import { Route as EarningsRouteImport } from './routes/earnings'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as BiometricRouteImport } from './routes/biometric'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignupServicesRouteImport } from './routes/signup.services'
import { Route as OnboardingStepRouteImport } from './routes/onboarding.$step'
import { Route as KycRejectedRouteImport } from './routes/kyc.rejected'
import { Route as KycPendingRouteImport } from './routes/kyc.pending'
import { Route as KycApprovedRouteImport } from './routes/kyc.approved'
import { Route as KycStepRouteImport } from './routes/kyc.$step'
import { Route as EarningsTaxDocumentsRouteImport } from './routes/earnings.tax-documents'
import { Route as EarningsRecentRouteImport } from './routes/earnings.recent'
import { Route as EarningsPayoutsRouteImport } from './routes/earnings.payouts'
import { Route as EarningsPayoutMethodRouteImport } from './routes/earnings.payout-method'
import { Route as BookingsIdRouteImport } from './routes/bookings.$id'
import { Route as EarningsPayoutsIdRouteImport } from './routes/earnings.payouts.$id'
import { Route as ApiPublicSeedDemoRouteImport } from './routes/api.public.seed-demo'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const SplashRoute = SplashRouteImport.update({
  id: '/splash',
  path: '/splash',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KycRoute = KycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EnableFaceidRoute = EnableFaceidRouteImport.update({
  id: '/enable-faceid',
  path: '/enable-faceid',
  getParentRoute: () => rootRouteImport,
} as any)
const EarningsRoute = EarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const BiometricRoute = BiometricRouteImport.update({
  id: '/biometric',
  path: '/biometric',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupServicesRoute = SignupServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => SignupRoute,
} as any)
const OnboardingStepRoute = OnboardingStepRouteImport.update({
  id: '/$step',
  path: '/$step',
  getParentRoute: () => OnboardingRoute,
} as any)
const KycRejectedRoute = KycRejectedRouteImport.update({
  id: '/rejected',
  path: '/rejected',
  getParentRoute: () => KycRoute,
} as any)
const KycPendingRoute = KycPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => KycRoute,
} as any)
const KycApprovedRoute = KycApprovedRouteImport.update({
  id: '/approved',
  path: '/approved',
  getParentRoute: () => KycRoute,
} as any)
const KycStepRoute = KycStepRouteImport.update({
  id: '/$step',
  path: '/$step',
  getParentRoute: () => KycRoute,
} as any)
const EarningsTaxDocumentsRoute = EarningsTaxDocumentsRouteImport.update({
  id: '/tax-documents',
  path: '/tax-documents',
  getParentRoute: () => EarningsRoute,
} as any)
const EarningsRecentRoute = EarningsRecentRouteImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => EarningsRoute,
} as any)
const EarningsPayoutsRoute = EarningsPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => EarningsRoute,
} as any)
const EarningsPayoutMethodRoute = EarningsPayoutMethodRouteImport.update({
  id: '/payout-method',
  path: '/payout-method',
  getParentRoute: () => EarningsRoute,
} as any)
const BookingsIdRoute = BookingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BookingsRoute,
} as any)
const EarningsPayoutsIdRoute = EarningsPayoutsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EarningsPayoutsRoute,
} as any)
const ApiPublicSeedDemoRoute = ApiPublicSeedDemoRouteImport.update({
  id: '/api/public/seed-demo',
  path: '/api/public/seed-demo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/biometric': typeof BiometricRoute
  '/bookings': typeof BookingsRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/earnings': typeof EarningsRouteWithChildren
  '/enable-faceid': typeof EnableFaceidRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/join': typeof JoinRoute
  '/kyc': typeof KycRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/signup': typeof SignupRouteWithChildren
  '/splash': typeof SplashRoute
  '/verify': typeof VerifyRoute
  '/welcome': typeof WelcomeRoute
  '/bookings/$id': typeof BookingsIdRoute
  '/earnings/payout-method': typeof EarningsPayoutMethodRoute
  '/earnings/payouts': typeof EarningsPayoutsRouteWithChildren
  '/earnings/recent': typeof EarningsRecentRoute
  '/earnings/tax-documents': typeof EarningsTaxDocumentsRoute
  '/kyc/$step': typeof KycStepRoute
  '/kyc/approved': typeof KycApprovedRoute
  '/kyc/pending': typeof KycPendingRoute
  '/kyc/rejected': typeof KycRejectedRoute
  '/onboarding/$step': typeof OnboardingStepRoute
  '/signup/services': typeof SignupServicesRoute
  '/api/public/seed-demo': typeof ApiPublicSeedDemoRoute
  '/earnings/payouts/$id': typeof EarningsPayoutsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/biometric': typeof BiometricRoute
  '/bookings': typeof BookingsRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/earnings': typeof EarningsRouteWithChildren
  '/enable-faceid': typeof EnableFaceidRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/join': typeof JoinRoute
  '/kyc': typeof KycRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/signup': typeof SignupRouteWithChildren
  '/splash': typeof SplashRoute
  '/verify': typeof VerifyRoute
  '/welcome': typeof WelcomeRoute
  '/bookings/$id': typeof BookingsIdRoute
  '/earnings/payout-method': typeof EarningsPayoutMethodRoute
  '/earnings/payouts': typeof EarningsPayoutsRouteWithChildren
  '/earnings/recent': typeof EarningsRecentRoute
  '/earnings/tax-documents': typeof EarningsTaxDocumentsRoute
  '/kyc/$step': typeof KycStepRoute
  '/kyc/approved': typeof KycApprovedRoute
  '/kyc/pending': typeof KycPendingRoute
  '/kyc/rejected': typeof KycRejectedRoute
  '/onboarding/$step': typeof OnboardingStepRoute
  '/signup/services': typeof SignupServicesRoute
  '/api/public/seed-demo': typeof ApiPublicSeedDemoRoute
  '/earnings/payouts/$id': typeof EarningsPayoutsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/biometric': typeof BiometricRoute
  '/bookings': typeof BookingsRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/earnings': typeof EarningsRouteWithChildren
  '/enable-faceid': typeof EnableFaceidRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/join': typeof JoinRoute
  '/kyc': typeof KycRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/signup': typeof SignupRouteWithChildren
  '/splash': typeof SplashRoute
  '/verify': typeof VerifyRoute
  '/welcome': typeof WelcomeRoute
  '/bookings/$id': typeof BookingsIdRoute
  '/earnings/payout-method': typeof EarningsPayoutMethodRoute
  '/earnings/payouts': typeof EarningsPayoutsRouteWithChildren
  '/earnings/recent': typeof EarningsRecentRoute
  '/earnings/tax-documents': typeof EarningsTaxDocumentsRoute
  '/kyc/$step': typeof KycStepRoute
  '/kyc/approved': typeof KycApprovedRoute
  '/kyc/pending': typeof KycPendingRoute
  '/kyc/rejected': typeof KycRejectedRoute
  '/onboarding/$step': typeof OnboardingStepRoute
  '/signup/services': typeof SignupServicesRoute
  '/api/public/seed-demo': typeof ApiPublicSeedDemoRoute
  '/earnings/payouts/$id': typeof EarningsPayoutsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/biometric'
    | '/bookings'
    | '/calendar'
    | '/earnings'
    | '/enable-faceid'
    | '/forgot-password'
    | '/home'
    | '/join'
    | '/kyc'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/sign-in'
    | '/signup'
    | '/splash'
    | '/verify'
    | '/welcome'
    | '/bookings/$id'
    | '/earnings/payout-method'
    | '/earnings/payouts'
    | '/earnings/recent'
    | '/earnings/tax-documents'
    | '/kyc/$step'
    | '/kyc/approved'
    | '/kyc/pending'
    | '/kyc/rejected'
    | '/onboarding/$step'
    | '/signup/services'
    | '/api/public/seed-demo'
    | '/earnings/payouts/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/biometric'
    | '/bookings'
    | '/calendar'
    | '/earnings'
    | '/enable-faceid'
    | '/forgot-password'
    | '/home'
    | '/join'
    | '/kyc'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/sign-in'
    | '/signup'
    | '/splash'
    | '/verify'
    | '/welcome'
    | '/bookings/$id'
    | '/earnings/payout-method'
    | '/earnings/payouts'
    | '/earnings/recent'
    | '/earnings/tax-documents'
    | '/kyc/$step'
    | '/kyc/approved'
    | '/kyc/pending'
    | '/kyc/rejected'
    | '/onboarding/$step'
    | '/signup/services'
    | '/api/public/seed-demo'
    | '/earnings/payouts/$id'
  id:
    | '__root__'
    | '/'
    | '/biometric'
    | '/bookings'
    | '/calendar'
    | '/earnings'
    | '/enable-faceid'
    | '/forgot-password'
    | '/home'
    | '/join'
    | '/kyc'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/sign-in'
    | '/signup'
    | '/splash'
    | '/verify'
    | '/welcome'
    | '/bookings/$id'
    | '/earnings/payout-method'
    | '/earnings/payouts'
    | '/earnings/recent'
    | '/earnings/tax-documents'
    | '/kyc/$step'
    | '/kyc/approved'
    | '/kyc/pending'
    | '/kyc/rejected'
    | '/onboarding/$step'
    | '/signup/services'
    | '/api/public/seed-demo'
    | '/earnings/payouts/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BiometricRoute: typeof BiometricRoute
  BookingsRoute: typeof BookingsRouteWithChildren
  CalendarRoute: typeof CalendarRoute
  EarningsRoute: typeof EarningsRouteWithChildren
  EnableFaceidRoute: typeof EnableFaceidRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HomeRoute: typeof HomeRoute
  JoinRoute: typeof JoinRoute
  KycRoute: typeof KycRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
  SignupRoute: typeof SignupRouteWithChildren
  SplashRoute: typeof SplashRoute
  VerifyRoute: typeof VerifyRoute
  WelcomeRoute: typeof WelcomeRoute
  ApiPublicSeedDemoRoute: typeof ApiPublicSeedDemoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/splash': {
      id: '/splash'
      path: '/splash'
      fullPath: '/splash'
      preLoaderRoute: typeof SplashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kyc': {
      id: '/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof KycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enable-faceid': {
      id: '/enable-faceid'
      path: '/enable-faceid'
      fullPath: '/enable-faceid'
      preLoaderRoute: typeof EnableFaceidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earnings': {
      id: '/earnings'
      path: '/earnings'
      fullPath: '/earnings'
      preLoaderRoute: typeof EarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biometric': {
      id: '/biometric'
      path: '/biometric'
      fullPath: '/biometric'
      preLoaderRoute: typeof BiometricRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/services': {
      id: '/signup/services'
      path: '/services'
      fullPath: '/signup/services'
      preLoaderRoute: typeof SignupServicesRouteImport
      parentRoute: typeof SignupRoute
    }
    '/onboarding/$step': {
      id: '/onboarding/$step'
      path: '/$step'
      fullPath: '/onboarding/$step'
      preLoaderRoute: typeof OnboardingStepRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/kyc/rejected': {
      id: '/kyc/rejected'
      path: '/rejected'
      fullPath: '/kyc/rejected'
      preLoaderRoute: typeof KycRejectedRouteImport
      parentRoute: typeof KycRoute
    }
    '/kyc/pending': {
      id: '/kyc/pending'
      path: '/pending'
      fullPath: '/kyc/pending'
      preLoaderRoute: typeof KycPendingRouteImport
      parentRoute: typeof KycRoute
    }
    '/kyc/approved': {
      id: '/kyc/approved'
      path: '/approved'
      fullPath: '/kyc/approved'
      preLoaderRoute: typeof KycApprovedRouteImport
      parentRoute: typeof KycRoute
    }
    '/kyc/$step': {
      id: '/kyc/$step'
      path: '/$step'
      fullPath: '/kyc/$step'
      preLoaderRoute: typeof KycStepRouteImport
      parentRoute: typeof KycRoute
    }
    '/earnings/tax-documents': {
      id: '/earnings/tax-documents'
      path: '/tax-documents'
      fullPath: '/earnings/tax-documents'
      preLoaderRoute: typeof EarningsTaxDocumentsRouteImport
      parentRoute: typeof EarningsRoute
    }
    '/earnings/recent': {
      id: '/earnings/recent'
      path: '/recent'
      fullPath: '/earnings/recent'
      preLoaderRoute: typeof EarningsRecentRouteImport
      parentRoute: typeof EarningsRoute
    }
    '/earnings/payouts': {
      id: '/earnings/payouts'
      path: '/payouts'
      fullPath: '/earnings/payouts'
      preLoaderRoute: typeof EarningsPayoutsRouteImport
      parentRoute: typeof EarningsRoute
    }
    '/earnings/payout-method': {
      id: '/earnings/payout-method'
      path: '/payout-method'
      fullPath: '/earnings/payout-method'
      preLoaderRoute: typeof EarningsPayoutMethodRouteImport
      parentRoute: typeof EarningsRoute
    }
    '/bookings/$id': {
      id: '/bookings/$id'
      path: '/$id'
      fullPath: '/bookings/$id'
      preLoaderRoute: typeof BookingsIdRouteImport
      parentRoute: typeof BookingsRoute
    }
    '/earnings/payouts/$id': {
      id: '/earnings/payouts/$id'
      path: '/$id'
      fullPath: '/earnings/payouts/$id'
      preLoaderRoute: typeof EarningsPayoutsIdRouteImport
      parentRoute: typeof EarningsPayoutsRoute
    }
    '/api/public/seed-demo': {
      id: '/api/public/seed-demo'
      path: '/api/public/seed-demo'
      fullPath: '/api/public/seed-demo'
      preLoaderRoute: typeof ApiPublicSeedDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BookingsRouteChildren {
  BookingsIdRoute: typeof BookingsIdRoute
}

const BookingsRouteChildren: BookingsRouteChildren = {
  BookingsIdRoute: BookingsIdRoute,
}

const BookingsRouteWithChildren = BookingsRoute._addFileChildren(
  BookingsRouteChildren,
)

interface EarningsPayoutsRouteChildren {
  EarningsPayoutsIdRoute: typeof EarningsPayoutsIdRoute
}

const EarningsPayoutsRouteChildren: EarningsPayoutsRouteChildren = {
  EarningsPayoutsIdRoute: EarningsPayoutsIdRoute,
}

const EarningsPayoutsRouteWithChildren = EarningsPayoutsRoute._addFileChildren(
  EarningsPayoutsRouteChildren,
)

interface EarningsRouteChildren {
  EarningsPayoutMethodRoute: typeof EarningsPayoutMethodRoute
  EarningsPayoutsRoute: typeof EarningsPayoutsRouteWithChildren
  EarningsRecentRoute: typeof EarningsRecentRoute
  EarningsTaxDocumentsRoute: typeof EarningsTaxDocumentsRoute
}

const EarningsRouteChildren: EarningsRouteChildren = {
  EarningsPayoutMethodRoute: EarningsPayoutMethodRoute,
  EarningsPayoutsRoute: EarningsPayoutsRouteWithChildren,
  EarningsRecentRoute: EarningsRecentRoute,
  EarningsTaxDocumentsRoute: EarningsTaxDocumentsRoute,
}

const EarningsRouteWithChildren = EarningsRoute._addFileChildren(
  EarningsRouteChildren,
)

interface KycRouteChildren {
  KycStepRoute: typeof KycStepRoute
  KycApprovedRoute: typeof KycApprovedRoute
  KycPendingRoute: typeof KycPendingRoute
  KycRejectedRoute: typeof KycRejectedRoute
}

const KycRouteChildren: KycRouteChildren = {
  KycStepRoute: KycStepRoute,
  KycApprovedRoute: KycApprovedRoute,
  KycPendingRoute: KycPendingRoute,
  KycRejectedRoute: KycRejectedRoute,
}

const KycRouteWithChildren = KycRoute._addFileChildren(KycRouteChildren)

interface OnboardingRouteChildren {
  OnboardingStepRoute: typeof OnboardingStepRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingStepRoute: OnboardingStepRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

interface SignupRouteChildren {
  SignupServicesRoute: typeof SignupServicesRoute
}

const SignupRouteChildren: SignupRouteChildren = {
  SignupServicesRoute: SignupServicesRoute,
}

const SignupRouteWithChildren =
  SignupRoute._addFileChildren(SignupRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BiometricRoute: BiometricRoute,
  BookingsRoute: BookingsRouteWithChildren,
  CalendarRoute: CalendarRoute,
  EarningsRoute: EarningsRouteWithChildren,
  EnableFaceidRoute: EnableFaceidRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HomeRoute: HomeRoute,
  JoinRoute: JoinRoute,
  KycRoute: KycRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
  SignupRoute: SignupRouteWithChildren,
  SplashRoute: SplashRoute,
  VerifyRoute: VerifyRoute,
  WelcomeRoute: WelcomeRoute,
  ApiPublicSeedDemoRoute: ApiPublicSeedDemoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
